---
- name: Update apt-cache
  apt:
    update_cache: true
    cache_valid_time: 7200

- name: Install rtpengine dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ debian_packages }}"

- name: Make source directory writeable.
  file:
    path: /usr/local/src
    state: directory
    mode: 0777

- name: Check out rtpengine.
  git:
    repo: https://github.com/sipwise/rtpengine.git
    dest: /usr/local/src/rtpengine
    version: "mr{{ rtp_engine_version }}"
    depth: 50
    accept_hostkey: yes
    force: yes
  become: no

- name: Build rtpengine.
  command:
    chdir: /usr/local/src/rtpengine
    argv: dpkg-buildpackage
  environment:
    DEB_BUILD_PROFILES: "pkg.ngcp-rtpengine.nobcg729"

- name: Install rtpengine debian packages.
  apt:
    deb: "/usr/local/src/{{ item }}"
  with_items: "{{ rtp_engine_debian_build_packages }}"

- name: Clean up rtpengine debian packages.
  ansible.builtin.file:
    path: "/usr/local/src/{{ item }}"
    state: absent
  with_items: "{{ rtp_engine_debian_build_packages }}"

- name: Create systemd unit file.
  template:
    src: rtpengine.service.j2
    dest: /etc/systemd/system/rtpengine.service
    mode: 0644
    owner: root
    group: root

- name: Systemctl daemon-reload.
  shell: systemctl daemon-reload

- name: Ensure rtpengine is set to start on boot.
  service:
    name: rtpengine
    enabled: yes
    state: restarted

- name: remove source code
  file:
    path: /usr/local/src/rtpengine
    state: absent
  when: remove_source|bool