---
- name: Check if rtpengine is installed.
  ansible.builtin.stat:
    path: /usr/sbin/rtpengine
  register: rtpengine_binary

- name: LOG
  ansible.builtin.debug:
    msg: "rtpengine binary exists"
  when: rtpengine_binary.stat.exists

- name: Ensure /var/log/rtpengine directory exists.
  ansible.builtin.file:
    path: /var/log/rtpengine
    state: directory
    owner: syslog
    group: adm
    mode: 0755

- name: Get the current rtpengine version.
  ansible.builtin.shell:
    cmd: "rtpengine --version 2>&1 | cut -c 10- | sed -e 's/\\+.*$//'"
  register: rtpengine_binary_version
  when: rtpengine_binary.stat.exists

- name: LOG
  ansible.builtin.debug:
    msg: "Current version of rtpengine is {{ rtpengine_binary_version.stdout }}"
  when: rtpengine_binary.stat.exists

- name: Update apt-cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 7200

- name: Install rtpengine dependencies.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ debian_packages }}"
  when: not rtpengine_binary.stat.exists or rtp_engine_version != rtpengine_binary_version.stdout

- name: Make source directory writeable.
  ansible.builtin.file:
    path: /usr/local/src/rtpengine_build
    state: directory
    mode: 0777
  when: not rtpengine_binary.stat.exists or rtp_engine_version != rtpengine_binary_version.stdout

- name: Check out rtpengine.
  ansible.builtin.git:
    repo: https://github.com/sipwise/rtpengine.git
    dest: /usr/local/src/rtpengine_build/rtpengine
    version: "mr{{ rtp_engine_version }}"
    depth: 50
    accept_hostkey: yes
    force: yes
  become: no
  when: not rtpengine_binary.stat.exists or rtp_engine_version != rtpengine_binary_version.stdout

- name: Build rtpengine.
  ansible.builtin.command:
    chdir: /usr/local/src/rtpengine_build/rtpengine
    argv: dpkg-buildpackage
  environment:
    DEB_BUILD_PROFILES: "pkg.ngcp-rtpengine.nobcg729"
  when: not rtpengine_binary.stat.exists or rtp_engine_version != rtpengine_binary_version.stdout

- name: Install rtpengine debian packages.
  ansible.builtin.apt:
    deb: "/usr/local/src/rtpengine_build/{{ item }}"
  with_items: "{{ rtp_engine_debian_build_packages }}"
  when: not rtpengine_binary.stat.exists or rtp_engine_version != rtpengine_binary_version.stdout

- name: Setup the logrotate strategy.
  ansible.builtin.copy:
    src: rtpengine.logrotate
    dest: /etc/logrotate.d/rtpengine
    mode: 0644
    owner: root
    group: root

- name: Setup the rsyslog for rtpengine.
  ansible.builtin.copy:
    src: 30-rtpengine.conf
    dest: /etc/rsyslog.d/30-rtpengine.conf
    mode: 0644
    owner: root
    group: root

- name: Create the prepare-rtpengine systemd file.
  ansible.builtin.copy:
    src: prepare-rtpengine.service
    dest: /etc/systemd/system/prepare-rtpengine.service
    mode: 0600
    owner: root
    group: root

- name: Create systemd unit file.
  ansible.builtin.template:
    src: rtpengine.service.j2
    dest: /etc/systemd/system/rtpengine.service
    mode: 0644
    owner: root
    group: root

- name: Ensure rtpengine is set to start on boot.
  ansible.builtin.systemd:
    name: rtpengine
    enabled: yes
    state: restarted

- name: remove source code
  ansible.builtin.file:
    path: /usr/local/src/rtpengine_build
    state: absent
  when: remove_source|bool