---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: 'vagrant'
      cachier: false
    box: generic/ubuntu2004
    memory: 512
    cpus: 1
    provision: no
provisioner:
  name: ansible
verifier:
  name: ansible
