---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-rtpengine
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
